{
    "name": "Hospital Management",
    "version": "15.0.1.0.0",
    "category": "Services",
    "summary": """Product catalog""",
    "license": "LGPL-3",
    "author": "Iva Boh",
    "maintainer": "https://github.com/IvaBoh",
    "website": "https://github.com/IvaBoh",
    "depends": ["base"],
    "data": [
        "security/ir.model.access.csv",
        "views/product_catalog_menus.xml",
        "views/res_partner_views.xml",
        "views/res_company_views.xml",
        "views/product_attribute_views.xml",
        "views/product_attribute_value_views.xml",
        "views/product_product_views.xml",
        # "views/hospital_disease_views.xml",
        # "views/hospital_patient_views.xml",
        # "views/hospital_patient_visit_multi_views.xml",
        # "views/hospital_physician_schedule_views.xml",
        # "views/hospital_diagnosis_views.xml",
        # "views/hospital_analysis_views.xml",
        # "wizard/hospital_physician_reassignment_views.xml",
        # "wizard/hospital_visit_reschedule_views.xml",
        # "wizard/hospital_create_schedule_views.xml",
        # "wizard/hospital_disease_analytic_report_views.xml",
        # "report/report_disease_count.xml",
        # "report/report.xml",
        # "report/physician_templates.xml",
        # "report/physician_reports.xml",
    ],
    "demo": [
        "data/res_partner_demo.xml",
        "data/res_company_demo.xml",
        "data/product_attribute_demo.xml",
        "data/product_attribute_value_demo.xml",
        # "data/product_product_demo.xml",
        # "data/hospital_patient_demo.xml",
        # "data/hospital_physician_demo.xml",
        # "data/hospital_diagnosis_demo.xml",
        # "data/hospital_physician_schedule_demo.xml",
        # "data/hospital_patient_visit_multi_demo.xml",
        # "data/hospital_analysis_demo.xml",
    ],
    "images": ["static/description/icon.png"],
    "support": "antutilo@gmail.com",
    "application": False,
    "installable": True,
    "auto_install": False,
}
