{
    "name": "Hospital Management",
    "version": "15.0.3.2.0",
    "category": "Services",
    "summary": """Odoo module to manage the basic processes of clinic""",
    "license": "LGPL-3",
    "author": "Iva Boh",
    "maintainer": "https://github.com/IvaBoh",
    "website": "https://github.com/IvaBoh",
    "depends": ["base"],
    "data": [
        "security/ir.model.access.csv",
        # "views/hr_hospital_menus.xml",
        # "views/hospital_disease_views.xml",
        # "views/hospital_patient_views.xml",
        # "views/hospital_physician_views.xml",
        # "views/hospital_patient_visit_multi_views.xml",
        # "views/hospital_physician_assign_history_views.xml",
        # "views/hospital_physician_schedule_views.xml",
        # "views/hospital_diagnosis_views.xml",
        # "views/hospital_analysis_views.xml",
        # "wizard/hospital_physician_reassignment_views.xml",
        # "wizard/hospital_visit_reschedule_views.xml",
        # "wizard/hospital_create_schedule_views.xml",
        # "wizard/hospital_disease_analytic_report_views.xml",
        # "report/report_disease_count.xml",
        # "report/report.xml",
        # "report/physician_templates.xml",
        # "report/physician_reports.xml",
    ],
    "demo": [
        # "data/hospital_disease_demo.xml",
        # "data/hospital_patient_demo.xml",
        # "data/hospital_physician_demo.xml",
        # "data/hospital_diagnosis_demo.xml",
        # "data/hospital_physician_schedule_demo.xml",
        # "data/hospital_patient_visit_multi_demo.xml",
        # "data/hospital_analysis_demo.xml",
    ],
    "images": ["static/description/icon.png"],
    "support": "antutilo@gmail.com",
    "application": False,
    "installable": True,
    "auto_install": False,
}
